#server:
#  port: 8080
#  servlet:
#    context-path: /
#
#spring:
#  datasource:
#    url: "jdbc:mysql://f4server.mysql.database.azure.com:3306/f4_delivery"
#    username: f4owner
#    password: Password@
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/f4delivery"
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true